mass: 0.5        # Wheel mass in Kg
radius: 0.05    # Wheel radius in m
length: 0.025  # Wheel length in m, considering is as a cylinder
# mesh: 'wheel.STL'          # Name of the mesh files. Leave it empty ('') to have a red wheel
mesh: ''
scale: ''
x_offset: 0.0
y_offset: 0.026
z_offset: -0.06
